export interface Activity {
  id: string;
  name: string;
  category: ActivityCategory;
  location: string;
  phone: string;
  website: string;
  social: string;
  description: string;
  tags: string[];
  priceRange: PriceRange;
  season: Season;
  groupSize: GroupSize;
  skillLevel: SkillLevel[];
  embedding?: number[];  // Generated by AgentDB
}

export type ActivityCategory =
  | 'surfing'
  | 'yoga'
  | 'diving'
  | 'kayaking'
  | 'cultural'
  | 'gastronomy'
  | 'golf'
  | 'equestrian'
  | 'watersports'
  | 'boat-tours'
  | 'wellness'
  | 'hiking'
  | 'cycling'
  | 'other';

export type PriceRange = '€' | '€€' | '€€€';

export type Season =
  | 'year-round'
  | 'summer'
  | 'winter'
  | 'april-october'
  | 'spring-fall';

export type GroupSize = 'small' | 'medium' | 'large';

export type SkillLevel = 'beginner' | 'intermediate' | 'advanced';

export interface ActivitySearchQuery {
  interests: string[];
  budget?: PriceRange;
  groupSize?: number;
  skillLevel?: SkillLevel;
  dates?: {
    arrival: string;
    departure: string;
  };
}

export interface ActivityRecommendation {
  activity: Activity;
  score: number;
  matchReasons: string[];
}
